export const USER_CREATED = "USER_CREATED";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const CREATE_BUSINESS_ACCOUNT = "CREATE_BUSINESS_ACCOUNT";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const CREATE_MEAL = "CREATE_MEAL";
export const FETCH_MEALS = "FETCH_MEALS";
